In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/well-being-dataset/well-being.csv

In [2]:
# read data into pandas dataframe

df = pd.read_csv('../input/well-being-dataset/well-being.csv')
df.head()

,Age (4 levels),Gender,French nationality,Field of study,Year of university,Learning disabilities,Difficulty memorizing lessons,Professional objective,Informed about opportunities,Satisfied with living conditions,...,Anxiety symptoms,Panic attack symptoms,Depressive symptoms,Cigarette smoker (5 levels),Cigarette smoker (3 levels),Drinker (3 levels),Drinker (2 levels),Binge drinking,Marijuana use,Other recreational drugs
0,20 and more,female,yes,humanities,second,no,no,yes,yes,yes,...,no,no,no,no,no,no,no or occasionally,no,no,no
1,19,female,yes,humanities,second,no,no,yes,yes,yes,...,no,no,no,regularly,occasionally to regularly,occasionally,no or occasionally,no,no,no
2,20 and more,female,yes,humanities,second,no,no,yes,yes,yes,...,no,no,yes,no,no,occasionally,no or occasionally,no,no,no
3,19,female,yes,humanities,second,no,no,yes,yes,yes,...,no,no,no,no,no,occasionally,no or occasionally,no,no,no
4,18,female,yes,humanities,second,no,no,yes,yes,yes,...,no,no,no,no,no,no,no or occasionally,no,no,no

# Clean dataset

In [3]:
# take out columns which are not relevant for this project

df2 = df.iloc[:, [9,17,25,28,52,53,54,55,57,60,61]]
df2

,Satisfied with living conditions,Financial difficulties,Eating junk food,Physical activity(3 levels),Anxiety symptoms,Panic attack symptoms,Depressive symptoms,Cigarette smoker (5 levels),Drinker (3 levels),Marijuana use,Other recreational drugs
0,yes,no,yes,regularly,no,no,no,no,no,no,no
1,yes,no,yes,regularly,no,no,no,regularly,occasionally,no,no
2,yes,no,yes,no,no,no,yes,no,occasionally,no,no
3,yes,no,yes,no,no,no,no,no,occasionally,no,no
4,yes,no,yes,no,no,no,no,no,no,no,no
...,...,...,...,...,...,...,...,...,...,...,...
4179,yes,no,yes,no,no,no,no,no,occasionally,no,no
4180,yes,no,yes,no,no,no,no,no,no,no,no
4181,yes,no,no,no,no,no,no,no,occasionally,no,no
4182,no,no,no,regularly,no,no,no,no,occasionally,yes,no
4183,no,no,yes,no,no,no,yes,no,occasionally,no,no

In [4]:
# check for null values

df2.isnull().sum()
df2

,Satisfied with living conditions,Financial difficulties,Eating junk food,Physical activity(3 levels),Anxiety symptoms,Panic attack symptoms,Depressive symptoms,Cigarette smoker (5 levels),Drinker (3 levels),Marijuana use,Other recreational drugs
0,yes,no,yes,regularly,no,no,no,no,no,no,no
1,yes,no,yes,regularly,no,no,no,regularly,occasionally,no,no
2,yes,no,yes,no,no,no,yes,no,occasionally,no,no
3,yes,no,yes,no,no,no,no,no,occasionally,no,no
4,yes,no,yes,no,no,no,no,no,no,no,no
...,...,...,...,...,...,...,...,...,...,...,...
4179,yes,no,yes,no,no,no,no,no,occasionally,no,no
4180,yes,no,yes,no,no,no,no,no,no,no,no
4181,yes,no,no,no,no,no,no,no,occasionally,no,no
4182,no,no,no,regularly,no,no,no,no,occasionally,yes,no
4183,no,no,yes,no,no,no,yes,no,occasionally,no,no

In [5]:
# remove null values

df2 = df2.dropna()
df2

,Satisfied with living conditions,Financial difficulties,Eating junk food,Physical activity(3 levels),Anxiety symptoms,Panic attack symptoms,Depressive symptoms,Cigarette smoker (5 levels),Drinker (3 levels),Marijuana use,Other recreational drugs
0,yes,no,yes,regularly,no,no,no,no,no,no,no
1,yes,no,yes,regularly,no,no,no,regularly,occasionally,no,no
2,yes,no,yes,no,no,no,yes,no,occasionally,no,no
3,yes,no,yes,no,no,no,no,no,occasionally,no,no
4,yes,no,yes,no,no,no,no,no,no,no,no
...,...,...,...,...,...,...,...,...,...,...,...
4179,yes,no,yes,no,no,no,no,no,occasionally,no,no
4180,yes,no,yes,no,no,no,no,no,no,no,no
4181,yes,no,no,no,no,no,no,no,occasionally,no,no
4182,no,no,no,regularly,no,no,no,no,occasionally,yes,no
4183,no,no,yes,no,no,no,yes,no,occasionally,no,no

In [6]:
# replace 'yes' and 'no' to 1 and 0

df2.replace(('yes', 'no'), (1, 0), inplace=True)
df2

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py:5244: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

,Satisfied with living conditions,Financial difficulties,Eating junk food,Physical activity(3 levels),Anxiety symptoms,Panic attack symptoms,Depressive symptoms,Cigarette smoker (5 levels),Drinker (3 levels),Marijuana use,Other recreational drugs
0,1,0,1,regularly,0,0,0,0,0,0,0
1,1,0,1,regularly,0,0,0,regularly,occasionally,0,0
2,1,0,1,0,0,0,1,0,occasionally,0,0
3,1,0,1,0,0,0,0,0,occasionally,0,0
4,1,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
4179,1,0,1,0,0,0,0,0,occasionally,0,0
4180,1,0,1,0,0,0,0,0,0,0,0
4181,1,0,0,0,0,0,0,0,occasionally,0,0
4182,0,0,0,regularly,0,0,0,0,occasionally,1,0
4183,0,0,1,0,0,0,1,0,occasionally,0,0

In [7]:
# replace objects with numerical values

df2.replace(('heavily', 'frequently', 'regularly', 'occasionally', 'no'), (4, 3, 2, 1, 0), inplace=True)
df2

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py:5244: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

,Satisfied with living conditions,Financial difficulties,Eating junk food,Physical activity(3 levels),Anxiety symptoms,Panic attack symptoms,Depressive symptoms,Cigarette smoker (5 levels),Drinker (3 levels),Marijuana use,Other recreational drugs
0,1,0,1,2,0,0,0,0,0,0,0
1,1,0,1,2,0,0,0,2,1,0,0
2,1,0,1,0,0,0,1,0,1,0,0
3,1,0,1,0,0,0,0,0,1,0,0
4,1,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
4179,1,0,1,0,0,0,0,0,1,0,0
4180,1,0,1,0,0,0,0,0,0,0,0
4181,1,0,0,0,0,0,0,0,1,0,0
4182,0,0,0,2,0,0,0,0,1,1,0
4183,0,0,1,0,0,0,1,0,1,0,0

In [8]:
# split target variable into seperate array

anxiety_X = df2.loc[:, df2.columns != 'Anxiety symptoms']
anxiety_y = df2['Anxiety symptoms'].to_numpy()

In [9]:
anxiety_X['Cigarette smoker (5 levels)'].unique()

array([0, 2, 1, 3, 4])

In [10]:
# build logistic regression model

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(anxiety_X, anxiety_y, test_size=0.3, random_state=0)
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [11]:
# evaluate performance

from sklearn import metrics

def evaluate_accuracy(model, X_test, y_test):
    y_pred = model.predict(X_test)
    return(model.score(X_test, y_test))

print('Accuracy of model: {:.2f}'.format(evaluate_accuracy(model, X_test, y_test)))

Accuracy of model: 0.91